use_frameworks!

platform :ios, '8.0'

target 'PublicDemo_Example' do
  pod 'PublicDemo', :path => '../'

  target 'PublicDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
